name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install Werkzeug

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flask
          pip install Werkzeug
          pip install pytest-flask

      - name: Run Tests
        run: |
          pytest --tb=short -v <<EOF
          - test: Register a new user
            method: POST
            endpoint: /register
            data:
              username: testuser
              password: testpassword
            expected_status_code: 302
            expected_redirect: /

          - test: Login with valid credentials
            method: POST
            endpoint: /login
            data:
              username: testuser
              password: testpassword
            expected_status_code: 302
            expected_redirect: /

          - test: Login with invalid credentials
            method: POST
            endpoint: /login
            data:
              username: testuser
              password: wrongpassword
            expected_status_code: 200
            expected_response_contains: Login

          - test: Add a new task
            setup:
              - method: POST
                endpoint: /login
                data:
                  username: testuser
                  password: testpassword
            method: POST
            endpoint: /add
            data:
              task: New Task
            expected_status_code: 302
            expected_redirect: /

          - test: Mark a task as completed
            setup:
              - method: POST
                endpoint: /add
                data:
                  task: New Task
            method: POST
            endpoint: /complete/0
            expected_status_code: 302
            expected_redirect: /

          - test: Delete an ongoing task
            setup:
              - method: POST
                endpoint: /add
                data:
                  task: New Task
            method: POST
            endpoint: /delete/0
            expected_status_code: 302
            expected_redirect: /

          - test: Delete a completed task
            setup:
              - method: POST
                endpoint: /add
                data:
                  task: Completed Task
              - method: POST
                endpoint: /complete/0
            method: POST
            endpoint: /delete_completed/0
            expected_status_code: 302
            expected_redirect: /

          - test: Logout
            setup:
              - method: POST
                endpoint: /login
                data:
                  username: testuser
                  password: testpassword
            method: POST
            endpoint: /logout
            expected_status_code: 302
            expected_redirect: /login
          EOF

  security_scanning:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit

      - name: Run Security Scan with Bandit
        run: bandit -r app.py

  dast_testing:
    runs-on: ubuntu-latest
    needs: security_scanning
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Test Environment
        run: |
          echo "Deploying to test environment..."
          # Add deployment commands here
          
      - name: Build and Run Flask App in Docker
        run: |
          docker build -t flask-app .
          docker run -d -p 5000:5000 flask-app
          sleep 10
          
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: "http://127.0.0.1:5000/"
            

  deploy:
    runs-on: ubuntu-latest
    needs: dast_testing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging environment..."
          # Add deployment commands here
