nama: Todo app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Todo app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      
      - name: Unit Tests
        run: mvn -B test --file app.py
      
      - name: Build the application
        run:
          mvn clean
          mvn -B test --file app.py
